AWSTemplateFormatVersion: '2010-09-09'
Description: Metrics, Alarms and Dashboard

Parameters:
  SNSTopicName:
    Description: SNS Topic name
    Type: String

  DashboardName:
    Description: Dashboard name
    Type: String

  CloudFormationTemplatesBucketName:
    Description: Bucket name
    Type: String

  CustomConfigurationsBucketName:
    Description: Bucket name
    Type: String

Resources:
  CloudFormationTemplatesBucketSizeBytesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: AWS/S3
      MetricName: BucketSizeBytes
      Dimensions:
        - Name: BucketName
          Value: !Ref CloudFormationTemplatesBucketName
        - Name: StorageType
          Value: StandardStorage
      AlarmName: !Sub "BucketSizeBytes of ${CloudFormationTemplatesBucketName}"
      AlarmDescription: !Sub "BucketSizeBytes of ${CloudFormationTemplatesBucketName} over the threshold"
      # InsufficientDataActions
      #   - !Ref SNSTopicName
      # OKActions:
      #   - !Ref SNSTopicName
      AlarmActions:
        - !Ref SNSTopicName
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 3
      Period: 300
      Statistic: Maximum
      Threshold: 1000000000
      TreatMissingData: missing

  CustomConfigurationsBucketSizeBytesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: AWS/S3
      MetricName: BucketSizeBytes
      Dimensions:
        - Name: BucketName
          Value: !Ref CustomConfigurationsBucketName
        - Name: StorageType
          Value: StandardStorage
      AlarmName: !Sub "BucketSizeBytes of ${CustomConfigurationsBucketName}"
      AlarmDescription: !Sub "BucketSizeBytes of ${CustomConfigurationsBucketName} over the threshold"
      # InsufficientDataActions
      #   - !Ref SNSTopicName
      # OKActions:
      #   - !Ref SNSTopicName
      AlarmActions:
        - !Ref SNSTopicName
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 3
      Period: 300
      Statistic: Maximum
      Threshold: 1000000000
      TreatMissingData: missing

  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Ref DashboardName
      DashboardBody: !Sub |
        {
            "widgets": [
                {
                    "type": "metric",
                    "x": 0,
                    "y": 0,
                    "width": 12,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "AWS/S3", "BucketSizeBytes", "StorageType", "StandardStorage", "BucketName", "${CloudFormationTemplatesBucketName}" ],
                            [ "AWS/S3", "BucketSizeBytes", "StorageType", "StandardStorage", "BucketName", "${CustomConfigurationsBucketName}" ]
                        ],
                        "region": "eu-west-1",
                        "title": "s3 - BucketSizeBytes"
                    }
                },
                {
                    "type": "metric",
                    "x": 12,
                    "y": 0,
                    "width": 12,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "AWS/S3", "NumberOfObjects", "StorageType", "AllStorageTypes", "BucketName", "${CloudFormationTemplatesBucketName}" ],
                            [ "AWS/S3", "NumberOfObjects", "StorageType", "AllStorageTypes", "BucketName", "${CustomConfigurationsBucketName}" ]
                        ],
                        "region": "eu-west-1",
                        "title": "s3 - NumberOfObjects"
                    }
                }
            ]
        }

Outputs:
  DashboardUrl:
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home#dashboards:name=${Dashboard}"
