AWSTemplateFormatVersion: '2010-09-09'
Description: Stack S3
Parameters:
  CloudFormationTemplatesBucketName:
    Description: Cloudformation templates bucket name
    Type: String

  CustomConfigurationsBucketName:
    Description: Custom configurations bucket name
    Type: String

Resources:
  CloudFormationTemplatesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref CloudFormationTemplatesBucketName

  CustomConfigurationsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref CustomConfigurationsBucketName
      VersioningConfiguration:
        Status: Enabled

Outputs:
  CloudFormationTemplatesBucketName:
    Description: Bucket name
    Value: !Ref CloudFormationTemplatesBucketName
  CustomConfigurationsBucketName:
    Description: Bucket name
    Value: !Ref CustomConfigurationsBucketName
