AWSTemplateFormatVersion: '2010-09-09'
Description: SNS Topic
Parameters:
  Project:
    Description: Project name
    Type: String
  EmailAddress:
    Description: Email address
    Type: String

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${Project}-notification"
      DisplayName: !Sub "${Project} Notification"
      Subscription:
      - Endpoint: !Ref EmailAddress
        Protocol: email

  SNSTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - events.amazonaws.com
            Action:
              - sns:Publish
            Resource: !Ref SNSTopic
      Topics:
        - !Ref SNSTopic

Outputs:
  SNSTopicName:
    Description: SNS topic name
    Value: !Ref SNSTopic
