AWSTemplateFormatVersion: '2010-09-09'
Description: VPC
Parameters:
  CidrBlock:
    Description: The set of IP addresses for the VPC
    Type: String
  EnableDnsSupport:
    Description: Indicates whether the instances launched in the VPC get DNS hostnames
    Type: String
  EnableDnsHostnames:
    Description: Indicates whether the DNS resolution is supported for the VPC
    Type: String
  InstanceTenancy:
    Description: The allowed tenancy of instances launched into the VPC
    Type: String
  VpcName:
    Description: VPC Name
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: !Ref EnableDnsSupport
      EnableDnsHostnames: !Ref EnableDnsHostnames
      InstanceTenancy: !Ref InstanceTenancy
      Tags:
      - Key: Name
        Value: !Ref VpcName

Outputs:
  CidrBlock:
    Description: The set of IP addresses for the VPC
    Value: !GetAtt VPC.CidrBlock
  # CidrBlockAssociations:
    # Description: A list of IPv4 CIDR block association IDs for the VPC
    # Value: !GetAtt VPC.CidrBlockAssociations
  DefaultNetworkAcl:
    Description: The default network ACL ID that is associated with the VPC
    Value: !GetAtt VPC.DefaultNetworkAcl
  DefaultSecurityGroup:
    Description: The default security group ID that is associated with the VPC
    Value: !GetAtt VPC.DefaultSecurityGroup
  # Ipv6CidrBlocks:
    # Description: A list of IPv6 CIDR blocks that are associated with the VPC
    # Value: !GetAtt VPC.Ipv6CidrBlocks
