template_path: production/cloudwatch.yaml
parameters:
  SNSTopicName: !stack_output production/sns.yaml::SNSTopicName
  DashboardName: {{ dashboard_name }}
  CloudFormationTemplatesBucketName: !stack_output production/s3.yaml::CloudFormationTemplatesBucketName
  CustomConfigurationsBucketName: !stack_output production/s3.yaml::CustomConfigurationsBucketName
